version: "3.8"

services:
  fastapi_app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - /mnt/d/IIITHCapstone/ASR-Wav2vec-Finetune:/app
      - /mnt/d/:/mnt/d
    runtime: nvidia  # Enable GPU support
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
